// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { simplePrompt } from "@sbaiahmed1/react-native-biometrics";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} reason - The reason for requesting authentication. If empty, the system default message is used.
 * @returns {Promise.<boolean>}
 */
export async function BiometricAuthentication(reason?: string): Promise<boolean> {
    // BEGIN USER CODE
    // Documentation https://github.com/sbaiahmed1/react-native-biometrics

    return simplePrompt(reason ?? "")
        .then(result => result.success)
        .catch(() => false);

    // END USER CODE
}
