// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { isSensorAvailable } from "@sbaiahmed1/react-native-biometrics";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @returns {Promise.<boolean>}
 */
export async function IsBiometricAuthenticationSupported(): Promise<boolean> {
    // BEGIN USER CODE
    // Documentation https://github.com/sbaiahmed1/react-native-biometrics

    return isSensorAvailable()
        .then(result => result.available)
        .catch(() => false);

    // END USER CODE
}
