// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * This JS Action takes a base64 String and a System.Image, decodes the base64 String and stores the resulting image in the System.Image object
 * @param {string} base64
 * @param {MxObject} image
 * @returns {Promise.<boolean>}
 */
export async function Base64DecodeToImage(base64: string, image: mendix.lib.MxObject): Promise<boolean> {
    // BEGIN USER CODE

    if (!base64) {
        throw new Error("base64 String should not be empty");
    }
    if (!image) {
        throw new Error("image should not be null");
    }

    const dataUri = base64.startsWith("data:") ? base64 : `data:image/png;base64,${base64}`;

    const res = await fetch(dataUri);
    const blob = await res.blob();

    return new Promise((resolve, reject) => {
        mx.data.saveDocument(image.getGuid(), "camera image", {}, blob, () => resolve(true), reject);
    });

    // END USER CODE
}
