// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Base64 } from "js-base64";
import RNBlobUtil from "react-native-blob-util";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * This JS Action takes a base64 String and a System.Image, decodes the base64 String and stores the resulting image in the System.Image object
 * @param {string} base64
 * @param {MxObject} image
 * @returns {Promise.<boolean>}
 */
export async function Base64DecodeToImage(base64: string, image: mendix.lib.MxObject): Promise<boolean> {
    // BEGIN USER CODE

    if (!base64) {
        throw new Error("base64 String should not be empty");
    }
    if (!image) {
        throw new Error("image should not be null");
    }

    // Native platform
    if (navigator && navigator.product === "ReactNative") {
        try {
            // Remove data URI prefix if present (e.g., "data:image/png;base64,")
            let cleanBase64 = base64;
            if (base64.includes(",")) {
                cleanBase64 = base64.split(",")[1];
            }

            // Remove any whitespace/newlines
            cleanBase64 = cleanBase64.replace(/\s/g, "");

            // Validate base64 format
            if (!/^[A-Za-z0-9+/]*={0,2}$/.test(cleanBase64)) {
                throw new Error("Invalid base64 format");
            }

            // Create a temporary file path
            const tempPath = `${RNBlobUtil.fs.dirs.CacheDir}/temp_image_${Date.now()}.png`;

            // Write Base64 data to a temporary file
            await RNBlobUtil.fs.writeFile(tempPath, cleanBase64, "base64");

            // Fetch the file as a blob
            const res = await fetch(`file://${tempPath}`);
            const blob = await res.blob();

            return new Promise((resolve, reject) => {
                mx.data.saveDocument(
                    image.getGuid(),
                    "camera image",
                    {},
                    blob,
                    () => {
                        RNBlobUtil.fs.unlink(tempPath).catch(() => {});
                        resolve(true);
                    },
                    error => {
                        RNBlobUtil.fs.unlink(tempPath).catch(() => {});
                        reject(error);
                    }
                );
            });
        } catch (error) {
            console.error("Failed to decode base64 to image:", error);
            return false;
        }
    }

    // Other platforms
    const blob = new Blob([Base64.toUint8Array(base64)], { type: "image/png" });
    return new Promise((resolve, reject) => {
        mx.data.saveDocument(image.getGuid(), "camera image", {}, blob, () => resolve(true), reject);
    });

    // END USER CODE
}
