documentation:
  - changed-files:
      - any-glob-to-all-files: ["*.md"]
Core:
  - changed-files:
      - any-glob-to-any-file:
          - .github/**/*
          - .husky/**/*
          - data/**/*
          - scripts/**/*
Widget:
  - changed-files:
      - any-glob-to-any-file:
          - packages/**/*-native*/**/*
          - packages/**/*_native*/**/*
test:
  - changed-files:
      - any-glob-to-all-files: ["*.spec.*"]
