documentation:
  - all: ["*.md"]
Core:
  - .github/**/*
  - .husky/**/*
  - data/**/*
  - scripts/**/*
Widget:
  - packages/**/*-native*/**/*
  - packages/**/*_native*/**/*
test:
  - all: ["*.spec.*"]
