changesetBaseRefs:
  - mx-version/10
  - origin/mx-version/10
  - upstream/mx-version/10
  - refs/remotes/origin/mx-version/10
  - +refs/heads/mx-version/10

compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.5.1.cjs
