/**
 * Host app entry: renders the Storybook UI itself rather than an app screen.
 *
 * `.storybook/index.tsx` is generated by `@storybook/react-native` from main.ts and the story
 * files — see the `storybook-generate` script in package.json.
 */
import { GestureHandlerRootView } from "react-native-gesture-handler";
import { SafeAreaProvider } from "react-native-safe-area-context";
import { StyleSheet } from "react-native";
import StorybookUI from "./.storybook";

function App() {
    return (
        <SafeAreaProvider>
            <GestureHandlerRootView style={styles.root}>
                <StorybookUI />
            </GestureHandlerRootView>
        </SafeAreaProvider>
    );
}

const styles = StyleSheet.create({
    root: {
        flex: 1,
        backgroundColor: "white"
    }
});

export default App;
