// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { watchPosition, unwatch, LocationError, GeolocationResponse } from "react-native-nitro-geolocation";
import { buildLocationOptions, mapPositionToMxObject } from "./utils";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * This action retrieves the current geographical position of a user/device with a minimum accuracy as parameter. If a position is not acquired with minimum accuracy within a specific timeout it will retrieve the last most precise location.
 *
 * Since this can compromise privacy, the position is not available unless the user approves it. The web browser will request the permission at the first time the location is requested. When denied by the user it will not prompt a second time.
 *
 * On hybrid and native platforms the permission should be requested with the `RequestLocationPermission` action.
 *
 * For good user experience, disable the nanoflow during action using property `Disabled during action` if you're using `Call a nanoflow button` to run JS Action `Get current location with minimum accuracy`.
 *
 * Best practices:
 * https://developers.google.com/web/fundamentals/native-hardware/user-location/
 * @param {Big} timeout - The maximum length of time (in milliseconds) the device is allowed to take in order to return a location. If empty, there is no timeout.
 * @param {Big} maximumAge - The maximum age (in milliseconds) of a possible cached position that is acceptable to return. If set to 0, it means that the device cannot use a cached position and must attempt to retrieve the real current position. By default the device will always return a cached position regardless of its age.
 * @param {boolean} highAccuracy - Use a higher accuracy method to determine the current location. Setting this to false saves battery life.
 * @param {Big} minimumAccuracy - The minimum accuracy to be received in meters. Less amount of meters, more precise is the location.
 * @returns {Promise.<MxObject>}
 */
export async function GetCurrentLocationMinimumAccuracy(
    timeout?: Big,
    maximumAge?: Big,
    highAccuracy?: boolean,
    minimumAccuracy?: number
): Promise<mendix.lib.MxObject> {
    // BEGIN USER CODE

    return new Promise((resolve, reject) => {
        const options = buildLocationOptions(timeout, maximumAge, highAccuracy);
        let lastAccruedPosition: GeolocationResponse | undefined;

        const timeoutMs = timeout ? timeout.toNumber() : 30000;
        const timeoutId = setTimeout(onTimeout, timeoutMs);
        const token = watchPosition(onSuccess, onError, options);

        function onTimeout(): void {
            unwatch(token);

            if (lastAccruedPosition) {
                createGeolocationObject(lastAccruedPosition);
            } else {
                reject(new Error("Timeout expired"));
            }
        }

        function onSuccess(position: GeolocationResponse): void {
            if (!minimumAccuracy || Number(minimumAccuracy) >= position.coords.accuracy) {
                clearTimeout(timeoutId);
                unwatch(token);
                createGeolocationObject(position);
            } else {
                if (!lastAccruedPosition || position.coords.accuracy < lastAccruedPosition.coords.accuracy) {
                    lastAccruedPosition = position;
                }
            }
        }

        function onError(error: LocationError): void {
            clearTimeout(timeoutId);
            unwatch(token);
            reject(new Error(error.message));
        }

        function createGeolocationObject(position: GeolocationResponse): void {
            mx.data.create({
                entity: "NanoflowCommons.Geolocation",
                callback: mxObject => resolve(mapPositionToMxObject(mxObject, position)),
                error: () =>
                    reject(new Error("Could not create 'NanoflowCommons.Geolocation' object to store location"))
            });
        }
    });

    // END USER CODE
}
