// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";
import { Platform } from "react-native";
import { getCurrentPosition, GeolocationResponse, LocationRequestOptions } from "react-native-nitro-geolocation";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * This action retrieves the current geographical position of a user/device.
 *
 * Since this can compromise privacy, the position is not available unless the user approves it. The web browser will request the permission at the first time the location is requested. When denied by the user it will not prompt a second time.
 *
 * On hybrid and native platforms the permission should be requested with the `RequestLocationPermission` action.
 *
 * Best practices:
 * https://developers.google.com/web/fundamentals/native-hardware/user-location/
 * @param {Big} timeout - The maximum length of time (in milliseconds) the device is allowed to take in order to return a location. If empty, there is no timeout.
 * @param {Big} maximumAge - The maximum age (in milliseconds) of a possible cached position that is acceptable to return. If set to 0, it means that the device cannot use a cached position and must attempt to retrieve the real current position. By default the device will always return a cached position regardless of its age.
 * @param {boolean} highAccuracy - Use a higher accuracy method to determine the current location. Setting this to false saves battery life.
 * @returns {Promise.<MxObject>}
 */
export async function GetCurrentLocation(
    timeout?: Big,
    maximumAge?: Big,
    highAccuracy?: boolean
): Promise<mendix.lib.MxObject> {
    // BEGIN USER CODE

    const options = buildLocationOptions(timeout, maximumAge, highAccuracy);
    try {
        const position = await getCurrentPosition(options);
        return new Promise((resolve, reject) => {
            mx.data.create({
                entity: "NanoflowCommons.Geolocation",
                callback: mxObject => {
                    resolve(mapPositionToMxObject(mxObject, position));
                },
                error: () =>
                    reject(new Error("Could not create 'NanoflowCommons.Geolocation' object to store location"))
            });
        });
    } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        return Promise.reject(new Error(`Could not get current location: ${message}`));
    }

    function buildLocationOptions(
        timeout: Big | undefined,
        maximumAge: Big | undefined,
        highAccuracy: boolean | undefined
    ): LocationRequestOptions {
        let timeoutNumber = timeout ? timeout.toNumber() : undefined;
        const maximumAgeNumber = maximumAge ? maximumAge.toNumber() : undefined;

        // If the timeout is 0 or undefined (empty), it causes a crash on iOS.
        // If the timeout is undefined (empty); we set timeout to 30 sec (default timeout)
        // If the timeout is 0; we set timeout to 1 hour (no timeout)
        if (Platform.OS === "ios") {
            if (timeoutNumber === undefined) {
                timeoutNumber = 30000;
            } else if (timeoutNumber === 0) {
                timeoutNumber = 3600000;
            }
        }

        return {
            timeout: timeoutNumber,
            maximumAge: maximumAgeNumber,
            accuracy: highAccuracy ? { android: "high", ios: "best" } : { android: "balanced", ios: "hundredMeters" }
        };
    }
    function mapPositionToMxObject(mxObject: mendix.lib.MxObject, pos: GeolocationResponse): mendix.lib.MxObject {
        mxObject.set("Timestamp", new Date(pos.timestamp));
        mxObject.set("Latitude", new Big(pos.coords.latitude.toFixed(8)));
        mxObject.set("Longitude", new Big(pos.coords.longitude.toFixed(8)));
        mxObject.set("Accuracy", new Big(pos.coords.accuracy.toFixed(8)));
        if (pos.coords.altitude != null) {
            mxObject.set("Altitude", new Big(pos.coords.altitude.toFixed(8)));
        }
        if (pos.coords.altitudeAccuracy != null && pos.coords.altitudeAccuracy !== -1) {
            mxObject.set("AltitudeAccuracy", new Big(pos.coords.altitudeAccuracy.toFixed(8)));
        }
        if (pos.coords.heading != null && pos.coords.heading !== -1) {
            mxObject.set("Heading", new Big(pos.coords.heading.toFixed(8)));
        }
        if (pos.coords.speed != null && pos.coords.speed !== -1) {
            mxObject.set("Speed", new Big(pos.coords.speed.toFixed(8)));
        }
        return mxObject;
    }

    // END USER CODE
}
