// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { check, request, PERMISSIONS, RESULTS, openSettings } from "react-native-permissions";
import { Platform, Alert, ToastAndroid } from "react-native";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * On the native platform a request for permission should be made before the `GetCurrentLocation` action would work.
 * @returns {Promise.<boolean>}
 */
export async function RequestLocationPermission(): Promise<boolean> {
    // BEGIN USER CODE

    const hasPermissionIOS = async (): Promise<boolean> => {
        const openSetting = (): void => {
            openSettings().catch(() => {
                Alert.alert("Unable to open settings.");
            });
        };

        const status = await request(PERMISSIONS.IOS.LOCATION_WHEN_IN_USE);

        if (status === RESULTS.GRANTED) {
            return true;
        }

        if (status === RESULTS.DENIED || status === RESULTS.BLOCKED) {
            Alert.alert("Location permission denied.");
        }

        if (status === RESULTS.UNAVAILABLE) {
            Alert.alert("Location Services must be enabled to determine your location.", "", [
                { text: "Go to Settings", onPress: openSetting },
                {
                    text: "Don't Use Location"
                }
            ]);
        }

        return false;
    };

    const hasPermissionAndroid = async (): Promise<boolean | undefined> => {
        if (typeof Platform.Version === "number" && Platform.Version < 23) {
            return true;
        }

        const status = await check(PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION);

        if (status === RESULTS.GRANTED) {
            return true;
        }

        const requestStatus = await request(PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION);

        if (requestStatus === RESULTS.GRANTED) {
            return true;
        }

        if (requestStatus === RESULTS.DENIED) {
            ToastAndroid.show("Location permission denied by user.", ToastAndroid.LONG);
        } else if (requestStatus === RESULTS.BLOCKED) {
            ToastAndroid.show("Location permission revoked by user.", ToastAndroid.LONG);
        }

        return false;
    };

    const hasLocationPermission = async (): Promise<boolean> => {
        if (Platform.OS === "ios") {
            const hasPermission = await hasPermissionIOS();
            return hasPermission;
        }

        if (Platform.OS === "android") {
            const hasPermission = await hasPermissionAndroid();
            return hasPermission ?? false;
        }

        return Promise.reject(new Error("Unsupported platform"));
    };

    if (navigator && navigator.product === "ReactNative") {
        return hasLocationPermission();
    } else if (navigator && navigator.geolocation) {
        return Promise.reject(new Error("No permission request for location is required for web/hybrid platform"));
    } else {
        return Promise.reject(new Error("Geolocation module could not be found"));
    }

    // END USER CODE
}
