// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { StatusBar, StatusBarAnimation, StatusBarStyle } from "react-native";

// BEGIN EXTRA CODE
// END EXTRA CODE

type Style = "DefaultStyle" | "LightContentStyle" | "DarkContentStyle";

/**
 * @param {"NativeMobileResources.StatusBarStyle.DefaultStyle"|"NativeMobileResources.StatusBarStyle.LightContentStyle"|"NativeMobileResources.StatusBarStyle.DarkContentStyle"} style - If empty, the current style is not changed.
 * @param {boolean} hidden
 * @param {boolean} animateChanges
 * @param {string} backgroundColor - If empty, the current background color is not changed.
 * @param {boolean} translucent
 * @param {boolean} networkActivityIndicatorVisible
 * @param {"NativeMobileResources.StatusBarHideShowAnimation.none"|"NativeMobileResources.StatusBarHideShowAnimation.fade"|"NativeMobileResources.StatusBarHideShowAnimation.slide"} animateHideShow - If empty, the default value 'none' is used.
 * @returns {Promise.<void>}
 */
export async function ChangeStatusBar(
    style?: Style,
    hidden?: boolean,
    animateChanges?: boolean,
    backgroundColor?: string,
    translucent?: boolean,
    networkActivityIndicatorVisible?: boolean,
    animateHideShow?: StatusBarAnimation
): Promise<void> {
    // BEGIN USER CODE

    if (style) {
        StatusBar.setBarStyle(mapStyleEnum(style), animateChanges);
    }

    if (hidden !== undefined) {
        StatusBar.setHidden(hidden, animateHideShow);
    }

    // React Native 0.88 removed the status bar background color, translucency and network activity
    // indicator APIs, as apps are always rendered edge-to-edge. These parameters no longer have any effect.
    if (backgroundColor || translucent || networkActivityIndicatorVisible) {
        console.warn(
            "ChangeStatusBar: the 'backgroundColor', 'translucent' and 'networkActivityIndicatorVisible' parameters are no longer supported and will be ignored."
        );
    }

    return Promise.resolve();

    function mapStyleEnum(styleEnum: Style): StatusBarStyle {
        switch (styleEnum) {
            case "DefaultStyle":
                return "default";
            case "LightContentStyle":
                return "light-content";
            case "DarkContentStyle":
                return "dark-content";
        }
    }

    // END USER CODE
}
