// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Platform } from "react-native";
import notifee, { AndroidChannel, AndroidImportance, Notification } from "@notifee/react-native";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Displays the specified notification straight away.
 *
 * Note: It is not possible to display a notification whilst the app is in the foreground on iOS 9.
 * @param {string} body - This field is required.
 * @param {string} title
 * @param {string} subtitle
 * @param {boolean} playSound
 * @param {string} actionName
 * @param {string} actionGuid
 * @returns {Promise.<void>}
 */
export async function DisplayNotification(
    body?: string,
    title?: string,
    subtitle?: string,
    playSound?: boolean,
    actionName?: string,
    actionGuid?: string
): Promise<void> {
    // BEGIN USER CODE
    if (!body) {
        throw new Error("Input parameter 'Body' is required");
    }

    const channelId = "mendix-local-notifications";
    await createNotificationChannelIfNeeded(channelId);

    const notification: Notification = {
        title: title || undefined,
        body,
        android: {
            channelId,
            // smallIcon: "ic_notification",
            ...(playSound ? { sound: "default" } : {})
        },
        ios: {
            ...(playSound ? { sound: "default" } : {})
        }
    };

    // Add subtitle for iOS (if provided)
    if (subtitle && Platform.OS === "ios") {
        notification.subtitle = subtitle;
    }

    // Add custom data (actionName and actionGuid) to the notification
    if (actionName || actionGuid) {
        notification.data = {
            actionName: actionName || null,
            guid: actionGuid || null
        };
    }

    await notifee.displayNotification(notification);

    async function createNotificationChannelIfNeeded(channelId: string): Promise<void> {
        if (Platform.OS === "android") {
            const channels = await notifee.getChannels();
            const isChannelExist = channels.some(c => c.name === channelId);
            if (!isChannelExist) {
                const channel: AndroidChannel = {
                    id: channelId,
                    name: "Local Notifications",
                    importance: AndroidImportance.HIGH
                };
                await notifee.createChannel(channel);
            }
        }
    }

    return Promise.resolve();
    // END USER CODE
}
