// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { NativeModules, Platform } from "react-native";
import notifee, {
    AndroidChannel,
    AndroidImportance,
    Notification,
    TimestampTrigger,
    TriggerType
} from "@notifee/react-native";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Displays the specified notification at a future moment in time.
 *
 * Note: It is not possible to display a notification whilst the app is in the foreground on iOS 9.
 * @param {Date} date - This field is required.
 * @param {string} body - This field is required.
 * @param {string} title
 * @param {string} subtitle
 * @param {boolean} playSound
 * @param {string} notificationId - This ID can be used to cancel the scheduled notification later.
 * @param {string} actionName
 * @param {string} actionGuid
 * @returns {Promise.<void>}
 */
export async function ScheduleNotification(
    date?: Date,
    body?: string,
    title?: string,
    subtitle?: string,
    playSound?: boolean,
    notificationId?: string,
    actionName?: string,
    actionGuid?: string
): Promise<void> {
    // BEGIN USER CODE
    if (!body) {
        throw new Error("Input parameter 'Body' is required");
    }

    if (!date) {
        throw new Error("Input parameter 'Date' is required");
    }

    // Documentation Documentation https://github.com/invertase/notifee
    if (NativeModules && !NativeModules.NotifeeApiModule) {
        return Promise.reject(new Error("Notifee native module is not available in your app"));
    }

    const channelId = playSound ? "mendix-local-notifications-withsound" : "mendix-local-notifications";
    await createNotificationChannelIfNeeded(channelId);

    const notification: Notification = {
        id: notificationId,
        title: title || undefined,
        body,
        android: { channelId, sound: "default" },
        ios: playSound ? { sound: "default" } : {}
    };

    if (subtitle && Platform.OS === "ios") {
        notification.subtitle = subtitle;
    }

    if (actionName || actionGuid) {
        notification.data = {
            actionName: actionName ?? "",
            guid: actionGuid ?? ""
        };
    }

    const trigger: TimestampTrigger = {
        type: TriggerType.TIMESTAMP,
        timestamp: date.getTime()
    };

    await notifee.createTriggerNotification(notification, trigger);

    async function createNotificationChannelIfNeeded(channelId: string): Promise<void> {
        if (Platform.OS === "ios") {
            return;
        }
        const existingChannel = await notifee.getChannel(channelId);
        const channel: AndroidChannel = {
            id: channelId,
            name: "Local Notifications",
            importance: AndroidImportance.HIGH,
            ...(playSound ? { sound: "default" } : {})
        };
        if (existingChannel === null) {
            await notifee.createChannel(channel);
        }
    }

    return Promise.resolve();
    // END USER CODE
}
