// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";
import { NativeModules, Platform } from "react-native";
import notifee from "@notifee/react-native";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {Big} badgeNumber - This field is required. Should be greater than or equal to 0.
 * @returns {Promise.<void>}
 */
export async function SetBadgeNumber(badgeNumber?: Big): Promise<void> {
    // BEGIN USER CODE
    // Documentation Documentation https://github.com/invertase/notifee

    const isIOS = Platform.OS === "ios";
    if (NativeModules && isIOS && !NativeModules.RNCPushNotificationIOS) {
        return Promise.reject(new Error("Notifications module is not available in your app"));
    }

    if (!badgeNumber) {
        return Promise.reject(new Error("Input parameter 'Badge number' is required"));
    }

    if (badgeNumber.lt(0)) {
        return Promise.reject(new Error("Input parameter 'Badge number' should be zero or greater"));
    }

    return notifee.setBadgeCount(badgeNumber as any as number);

    // END USER CODE
}
