// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} widgetName
 * @returns {Promise.<void>}
 */
export async function JS_Signature_Read(widgetName) {
    // BEGIN USER CODE
    if (!widgetName) {
        throw new Error("Parameter 'Widget Name' is required");
    }
    const signatureWidgets = globalThis.__com_mendix_widget_native_signature;
    if (signatureWidgets === undefined) {
        throw new Error("'Signature' widget is required to be loaded before calling this action.");
    }
    if (signatureWidgets[widgetName] === undefined) {
        throw new Error("No 'Signature' widget available with 'Name': " + widgetName);
    }
    signatureWidgets[widgetName].read();

    // END USER CODE
}
