name: "Setup Python Common"
description: "Setup Python and install dependencies"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: '3.12'
    - run: pip install PyYAML httplib2
      shell: bash