name: "Setup Python Common"
description: "Setup Python and install dependencies"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
      with:
        python-version: '3.12'
    - run: pip install PyYAML httplib2
      shell: bash