// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {MxObject} file - File object which will be downloaded.
 * @param {boolean} showFileInBrowser - Set to True to let the browser open the file in a new tab.
 * Set to False if the file only needs to be downloaded to the device storage.
 * @returns {Promise.<void>}
 */
export async function DownloadWebFile(file?: mendix.lib.MxObject, showFileInBrowser?: boolean) {
    // BEGIN USER CODE
    if (!file) {
        return Promise.reject(new Error("Input parameter 'file' is required"));
    }

    const target = showFileInBrowser ? "window" : "internal";

    return new Promise((resolve, reject) => {
        mx.ui
            .downloadFile({
                mxobject: file,
                target,
                error: (err: Error) => reject(err)
            })
            .then(resolve)
            .catch(reject);
    });
    // END USER CODE
}
