/* eslint-disable @typescript-eslint/explicit-function-return-type */

import colors from "colors";
import fg from "fast-glob";
import { mkdirSync } from "fs";
import { createRequire } from "module";
import { basename, dirname, join, posix, relative, sep } from "path";
import copy from "recursive-copy";
import clear from "rollup-plugin-clear";
import command from "rollup-plugin-command";
import { promisify } from "util";
import { nodeResolve } from "@rollup/plugin-node-resolve";
import typescript from "@rollup/plugin-typescript";
import { collectDependencies, copyJsModule } from "./rollup-plugin-collect-dependencies.mjs";
import { licenseCustomTemplate, copyLicenseFile } from "./rollup-helper.mjs";

const cwd = process.cwd();

export default async args => {
    const require = createRequire(import.meta.url);
    const jsActionTargetFolder = `javascriptsource/${args.configProject ?? "nativemobileresources"}/actions`;
    const result = [];
    const posixPath = join(cwd, "src", "**/*.ts").split(sep).join(posix.sep); // Always use forward slashes
    const files = await fg([posixPath]); // fast-glob only works with forward slashes
    const outDir = join(cwd, "dist");

    const nodeResolvePlugin = nodeResolve({ preferBuiltins: false, mainFields: ["module", "browser", "main"] });
    const typescriptPlugin = typescript({
        noEmitOnError: false,
        sourceMap: false,
        inlineSources: false,
        target: "es2019",
        types: ["mendix-client", "react-native"],
        allowSyntheticDefaultImports: true,
        compilerOptions: {
            newLine: "CRLF"
        }
    });

    const copyAsync = promisify(copy);

    // Inline plugin to prepare JS actions for Studio Pro format
    const studioProFormatPlugin = {
        name: "studio-pro-format",
        generateBundle(options, bundle) {
            for (const [fileName, chunk] of Object.entries(bundle)) {
                if (chunk.type !== "chunk" || !fileName.endsWith(".js")) continue;

                let code = chunk.code;

                // 1. Check if header exists and remove it (we'll add it back at line 1)
                const hasHeader = code.includes("// This file was generated by Mendix Studio Pro.");
                if (hasHeader) {
                    // Remove existing header (7 lines)
                    code = code.replace(
                        /^\/\/ This file was generated by Mendix Studio Pro\.\r?\n\/\/\r?\n\/\/ WARNING: Only the following code will be retained when actions are regenerated:\r?\n\/\/ - the import list\r?\n\/\/ - the code between BEGIN USER CODE and END USER CODE\r?\n\/\/ - the code between BEGIN EXTRA CODE and END EXTRA CODE\r?\n\/\/ Other code you write will be lost the next time you deploy the project\.\r?\n/m,
                        ""
                    );
                }

                // 2. Remove Big import (will add back at line 8 with header)
                const hasBigImport = code.match(/^import\s*\{\s*Big\s*\}\s*from\s*["']big\.js["'];?\s*$/m);
                if (hasBigImport) {
                    code = code.replace(/^import\s*\{\s*Big\s*\}\s*from\s*["']big\.js["'];?\s*\r?\n/m, "");
                }

                // 3. Add header at line 1 + Big import at line 8
                const header = [
                    "// This file was generated by Mendix Studio Pro.",
                    "//",
                    "// WARNING: Only the following code will be retained when actions are regenerated:",
                    "// - the import list",
                    "// - the code between BEGIN USER CODE and END USER CODE",
                    "// - the code between BEGIN EXTRA CODE and END EXTRA CODE",
                    "// Other code you write will be lost the next time you deploy the project.",
                    'import { Big } from "big.js";'
                ].join("\r\n") + "\r\n";

                code = header + code;

                // 4. Add missing // BEGIN EXTRA CODE if // END EXTRA CODE exists without a BEGIN
                if (code.includes('// END EXTRA CODE') && !code.includes('// BEGIN EXTRA CODE')) {
                    // Find last import line, add BEGIN EXTRA CODE after it
                    code = code.replace(/(^import .+$)/m, '$1\n\n// BEGIN EXTRA CODE');
                }

                // 5. If no EXTRA CODE markers at all, add empty block after imports
                if (!code.includes('// BEGIN EXTRA CODE') && !code.includes('// END EXTRA CODE')) {
                    code = code.replace(/(^import .+$)(\r?\n)+(?=\/?\*\*|export)/m, '$1\n\n// BEGIN EXTRA CODE\n// END EXTRA CODE\n\n');
                }

                // 6. Fix export pattern: async function Name { } export { Name };
                //    → export async function Name { }
                const exportMatch = code.match(/export\s*\{\s*(\w+)\s*\};?\s*$/m);
                if (exportMatch) {
                    const functionName = exportMatch[1];
                    const funcPattern = new RegExp(`^(async\\s+function\\s+${functionName}\\s*\\()`, "m");
                    code = code.replace(funcPattern, "export $1");
                    code = code.replace(/\nexport\s*\{\s*\w+\s*\};?\s*$/m, "");
                }

                // 7. Fix USER CODE marker indentation: Studio Pro uses tabs inside functions
                //    Match any whitespace before the markers and replace with single tab
                code = code.replace(/^[ \t]+(\/\/ BEGIN USER CODE)/gm, "\t$1");
                code = code.replace(/^[ \t]+(\/\/ END USER CODE)/gm, "\t$1");

                // 8. Ensure blank line before // BEGIN EXTRA CODE
                code = code.replace(/([^\r\n])\r?\n(\/\/ BEGIN EXTRA CODE)/g, "$1\r\n\r\n$2");

                // 9. Ensure blank line after // END EXTRA CODE
                code = code.replace(/(\/\/ END EXTRA CODE)\r?\n([^\r\n])/g, "$1\r\n\r\n$2");

                // 10. Normalize JSDoc formatting to match Studio Pro
                //     - Empty JSDoc lines: ` *` (one space before asterisk, nothing after)
                //     - Lines with text: ` * text` (one space before, one space after asterisk)
                code = code.replace(/^[ \t]+\*[ \t]+$/gm, " *");  // Empty JSDoc lines: remove trailing whitespace
                code = code.replace(/^[ \t]+\*[ \t]+(.+)$/gm, " * $1");  // JSDoc with text: normalize to 1 space before and after asterisk

                // 11. Normalize all line endings to CRLF (Studio Pro expects \r\n everywhere)
                code = code.replace(/\r?\n/g, "\r\n");

                chunk.code = code;
            }
        }
    };

    files.forEach((file, i) => {
        const fileInput = relative(cwd, file);
        const fileOutput = basename(file, ".ts");
        result.push({
            input: fileInput,
            output: {
                format: "es",
                file: join(outDir, `${fileOutput}.js`),
                sourcemap: false
            },
            external: nativeExternal,
            plugins: [
                i === 0 ? clear({ targets: [outDir] }) : null,
                collectDependencies({
                    copyJsModules: true,
                    onlyNative: false,
                    outputDir: outDir,
                    widgetName: fileOutput,
                    licenseOptions: {
                        thirdParty: {
                            includePrivate: true,
                            output: [
                                {
                                    file: join(outDir, "dependencies.txt")
                                },
                                {
                                    file: join(outDir, "dependencies.json"),
                                    template: licenseCustomTemplate
                                }
                            ]
                        }
                    }
                }),
                nodeResolvePlugin,
                typescriptPlugin,
                studioProFormatPlugin,
                i === files.length - 1
                    ? command([
                          async () => copyLicenseFile(cwd, outDir),
                          async () => {
                              if (args.configProject === "nativemobileresources") {
                                  // `fbjs/lib/invariant` is being used silently by @react-native-community/cameraroll; it is not listed as a dependency nor peerDependency.
                                  // https://github.dev/react-native-cameraroll/react-native-cameraroll/blob/7c269a837d095a2cb5f4ce13b54ab3060455b17f/js/CameraRoll.js#L14
                                  const path = join(outDir, "node_modules", "fbjs", "lib");
                                  mkdirSync(path, { recursive: true });
                                  await copyAsync(
                                      join(dirname(require.resolve("fbjs")), "lib", "invariant.js"),
                                      join(path, "invariant.js"),
                                      {
                                          overwrite: true
                                      }
                                  );
                              } else if (args.configProject === "nanoflowcommons") {
                                  // `invariant` is being used silently by @react-native-community/geolocation; it is not listed as a dependency nor peerDependency.
                                  // https://github.dev/react-native-geolocation/react-native-geolocation/blob/1786929f2be581da91082ff857c2393da5e597b3/js/implementation.native.js#L13
                                  await copyAsync(
                                      dirname(require.resolve("invariant")),
                                      join(outDir, "node_modules", "invariant"),
                                      {
                                          overwrite: true
                                      }
                                  );
                              }

                              // this is helpful to copy the files and folders to a test project path for dev/testing purposes.
                              if (process.env.MX_PROJECT_PATH) {
                                  const destination = join(process.env.MX_PROJECT_PATH, jsActionTargetFolder);
                                  mkdirSync(destination, { recursive: true });
                                  copy(outDir, destination, { filter: ["**/*"], overwrite: true });
                              }
                          }
                      ])
                    : null
            ],
            onwarn
        });
    });

    return result;

    function onwarn(warning) {
        const description =
            (warning.plugin ? `(${warning.plugin} plugin) ` : "") +
            (warning.loc ? `${relative(cwd, warning.loc.file)} (${warning.loc.line}:${warning.loc.column}) ` : "") +
            `Error: ${warning.message}` +
            (warning.frame ? warning.frame : "");

        // Many rollup warnings are indication of some critical issue, so we should treat them as errors,
        // except a short white-list which we know is safe _and_ not easily fixable.
        if (["CIRCULAR_DEPENDENCY", "THIS_IS_UNDEFINED", "UNUSED_EXTERNAL_IMPORT"].includes(warning.code)) {
            console.warn(colors.yellow(description));
        } else if (args.watch) {
            // Do not break watch mode because of an error. Also don't use console.error, since it is overwritten by rollup
            console.warn(colors.red(description));
        } else {
            console.error(colors.red(description));
            process.exit(1);
        }
    }
};

const nativeExternal = [
    /^mendix\//,
    /^react-native(\/|$)/,
    /^react-native-windows(\/|$)/,
    /^react-native-web(\/|$)/,
    "big.js",
    "react",
    /react-native-gesture-handler\/*/,
    /^react-native-reanimated(\/|$)/,
    /^react-native-worklets(\/|$)/,
    /^react-native-svg(\/|$)/,
    /^@react-native-vector-icons(\/|$)/,
    /^@?react-navigation($|\/)/,
    /^react-native-device-info(\/|$)/
];
