name: "Start the runtime"
description: "Start the runtime in preparation of the native e2e tests"
inputs:
  mda-file:
    description: "Path to the deployment package"
    required: true
  mendix-version:
    description: "Mendix version to use for the runtime"
    required: true
runs:
  using: composite
  steps:
    - name: "Setup Python"
      uses: actions/setup-python@v4.5.0
      with:
        python-version: "3.x"

    - name: "Install Python dependencies"
      run: pip install pyaml httplib2
      shell: bash

    - name: "Setup Java 21"
      id: setup-java
      uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 #v4
      with:
        distribution: "temurin"
        java-version: "21"
    
    - name: "Make setup-runtime.sh executable"
      run: chmod +x .github/scripts/setup-runtime.sh
      shell: bash

    - name: "Initial setup"
      run: |
        .github/scripts/setup-runtime.sh "${{ inputs.mda-file }}" "${{ inputs.mendix-version }}" "${{ steps.setup-java.outputs.path }}" "${{ github.workspace }}"
      shell: bash

    - name: "Start mxruntime with retries"
      run: |
        set -e
        MAX_RETRIES=3
        RETRY=0
        until bin/m2ee -c ${{ github.workspace }}/project/m2ee-native.yml --verbose --yolo start; do
          RETRY=$((RETRY+1))
          if [ $RETRY -ge $MAX_RETRIES ]; then
            echo "mxruntime failed after $MAX_RETRIES attempts."
            exit 1
          fi
          echo "mxruntime failed, retrying ($RETRY/$MAX_RETRIES)..."
          .github/scripts/setup-runtime.sh "${{ inputs.mda-file }}" "${{ inputs.mendix-version }}" "${{ steps.setup-java.outputs.path }}" "${{ github.workspace }}"
        done
      shell: bash