name: Create Release For Atlas Theme Folder

on:
    push:
        branches: [master]
        paths:
            - packages/theming/atlas/src/theme/**/*

    workflow_dispatch:

jobs:
    build:
        name: Create Release For Atlas Theme Folder
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                  submodules: false
            - name: "Defining cache"
              uses: actions/cache@v2
              env:
                  cache-name: cache-node-modules
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
            - name: "Installing dependencies"
              run: npm install
            - name: "Compile TS to JS"
              run: |
                  cd packages/theming/atlas
                  npm run release-ts
            - name: "Release Atlas Theme Files"
              uses: "marvinpinto/action-automatic-releases@latest"
              with:
                  repo_token: "${{ secrets.GITHUB_TOKEN }}"
                  automatic_release_tag: "test-atlas"
                  prerelease: false
                  title: "Test Release"
                  files: |
                      packages/theming/atlas/dist/theme/native/main.js
                      packages/theming/atlas/dist/theme/native/custom-variables.js
                      packages/theming/atlas/src/theme/web/**/*
