name: Marketplace Release

on:
  push:
    tags:
      - "*-native-v*"

jobs:
  publish_release:
    name: "Marketplace Release"
    runs-on: ubuntu-latest

    steps:
      - name: "Checking-out code"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: false
      - name: "Defining Environment Variables"
        id: variables
        run: echo "tag=$(git tag --points-at HEAD)" >> ${{ runner.os == 'Windows' && '$env:GITHUB_OUTPUT' || '$GITHUB_OUTPUT' }}
      - name: "Defining scope"
        uses: jungwinter/split@7f51d99e7cc1f147f6f99be75acf5e641930af88 # v2.1.0
        id: scope
        with:
          msg: "${{ steps.variables.outputs.tag }}"
          seperator: "-v"
      - name: "Defining node version"
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: ".nvmrc"
          package-manager-cache: false
      - name: "Setup pnpm"
        uses: pnpm/action-setup@a8198c4bff370c8506180b035930dea56dbd5288 # v5
      - name: "Installing dependencies"
        run: pnpm install
      - name: "Building native widgets and js actions"
        run: pnpm -r run release
      - name: "Updating Native Mobile Resources project"
        run: pnpm run create-modules
        env:
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
          GH_EMAIL: ${{ secrets.GH_EMAIL }}
          GH_NAME: ${{ secrets.GH_NAME }}
          GH_PAT: ${{ secrets.GH_PAT }}
          TAG: ${{ steps.variables.outputs.tag }}
      - name: "Check changes and publish package ${{ steps.variables.outputs.tag }}"
        run: pnpm --filter=${{ steps.scope.outputs._0 }} run release:marketplace
        env:
          OPENID_URL: ${{ secrets.OPENID_URL }}
          CPAPI_USERNAME: ${{ secrets.CPAPI_USERNAME }}
          CPAPI_PASS_PROD: ${{ secrets.CPAPI_PASS_PROD }}
          TAG: ${{ steps.variables.outputs.tag }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Send slack msg on failure"
        if: ${{ failure() }}
        uses: ./.github/actions/slack-notification
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          message: |
            :warning: *Automation Failed*

            Something went wrong while uploading version ${{ steps.scope.outputs._1 }} of package ${{ steps.scope.outputs._0 }} to the marketplace. <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|More info..>
          bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
