name: "Pull Request Labeler"
on:
  - pull_request_target #always checks the configuration from the target branch, for source branch change this to pull_request

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b # v6.0.1
        with:
          repo-token: ${{ secrets.GH_PAT }}
          configuration-path: ".github/configs/labeler.yml"
